AWSTemplateFormatVersion: 2010-09-09
Description: HashiCorp Vault EC2 Linux Template

Parameters:
  InstanceType:
    Type: String
    Default: t2.medium
  AMI:
    Type: String
    Default: ami-cfe4b2b0 #Amazon Linux 1
  InstanceSubnet:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-29a8084e
  # Default: ami-0c7a470a5d6953944

Resources:
#Add Security Group for cluster communication and client access to Vault
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
      RoleName: Vault-DynamoDB-Access

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole
      InstanceProfileName: DynamoDBInstanceProfile

  SecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows ports inbound for SSH
      GroupName: krausen-ssh-home
      VpcId: vpc-004ea47a
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: "12.172.230.255/32"

  VaultInternalCommunicationSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows ports inbound for Vault Communication
      GroupName: vault-internal-sg
      VpcId: vpc-004ea47a
      SecurityGroupIngress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: "10.0.11.0/24"

  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: !Ref InstanceType
      InstanceInitiatedShutdownBehavior: stop
      ImageId: !Ref AMI
      KeyName: Krausen-US-East-1-Demo
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          DeviceIndex: "0"
          SubnetId: !Ref InstanceSubnet
          GroupSet:
            - !Ref SecGroup
            - !Ref VaultInternalCommunicationSG
          PrivateIpAddress: 10.0.11.80
      Tags:
      - Key: "Name"
        Value: "Vault-Node-01"
      UserData:
        Fn::Base64:
          !Sub |
            #! /bin/bash -xe
            yum install python-pip -y
            yum install git -y
            cd /usr/local/bin
            git clone https://github.com/hashicorp/terraform-aws-vault.git
            terraform-aws-vault/modules/install-vault/install-vault --version 0.10.2
            wget -P /opt/vault/config https://raw.githubusercontent.com/btkrausen/AWS/master/Vault/config-a.hcl
            export PATH=$PATH:/usr/local/bin

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType: !Ref InstanceType
      InstanceInitiatedShutdownBehavior: stop
      ImageId: !Ref AMI
      KeyName: Krausen-US-East-1-Demo
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          DeviceIndex: "0"
          SubnetId: !Ref InstanceSubnet
          GroupSet:
            - !Ref SecGroup
            - !Ref VaultInternalCommunicationSG
          PrivateIpAddress: 10.0.11.81
      Tags:
      - Key: "Name"
        Value: "Vault-Node-02"
      UserData:
        Fn::Base64:
          !Sub |
            #! /bin/bash -xe
            yum install python-pip -y
            yum install git -y
            cd /usr/local/bin
            git clone https://github.com/hashicorp/terraform-aws-vault.git
            terraform-aws-vault/modules/install-vault/install-vault --version 0.10.2
            wget -P /opt/vault/config https://raw.githubusercontent.com/btkrausen/AWS/master/Vault/config-b.hcl
            export PATH=$PATH:/usr/local/bin
