AWSTemplateFormatVersion: '2010-09-09'
Description: 'Windows Bastion Host'

Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC in which to launch the instance

  InstanceSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet in which to launch the instance

  EC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the EC2 Key Pair to use for instance

  PublicIP:
    Type: String
    Description: Enter Public IP address from which to restrict RDP traffic (e.g., 12.34.56.78/32)
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: Value must be in the format of <ip address>/<cidr>

Mappings:

  WindowsServer:
    us-east-1:
      "AMI": "ami-603b1c1a"
    us-east-2:
      "AMI": "ami-16370073"
    us-west-1:
      "AMI": "ami-e8b6be88"
    us-west-2:
      "AMI": "ami-74800e0c"

Resources:

  WindowsBastionHost:
    Type: AWS::EC2::Instance
    DependsOn:
      - WindowsRDPSecurityGroup
    Properties:
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs:
            Ref: AWS::Region
      ImageId: !FindInMap [WindowsServer, !Ref "AWS::Region", AMI]
      InstanceType: t2.medium
      KeyName: !Ref EC2KeyPair
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: WindowsRDPSecurityGroup
          SubnetId:
            Ref: InstanceSubnet
      Tags:
      - Key: "Name"
        Value: "Windows Bastion"
      - Key: "Environment"
        Value: "Management"
      - Key: "Application"
        Value: "Windows Server"

  WindowsRDPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows port inbound for html
      GroupName: windows-bastion-rdp
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3389'
        ToPort: '3389'
        CidrIp: !Ref PublicIP
